name: tg-notify

# Controls when the workflow will run
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #Request
     - name: Telegram Notify request
       if: ${{ github.event_name == 'pull_request' }}
       uses: appleboy/telegram-action@v0.0.8
       with:
         to: ${{ secrets.TELEGRAM_TO }}
         token: ${{ secrets.TELEGRAM_TOKEN }}
         format: markdown
         message: | #https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#github-context
          *${{ github.actor }}*
          Pushed to pull request: *${{ github.event.pull_request.title }}* 
          In repository: *${{ github.repository }}*
          🔗 ${{ github.event.pull_request.html_url }}
